package com.goku.webservice.model;

public class gokuAuthority extends gokuAuthorityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_authority.auth
     *
     * @mbg.generated
     */
    private String auth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_authority.auth
     *
     * @return the value of goku_authority.auth
     *
     * @mbg.generated
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_authority.auth
     *
     * @param auth the value for goku_authority.auth
     *
     * @mbg.generated
     */
    public void setAuth(String auth) {
        this.auth = auth == null ? null : auth.trim();
    }
}