package com.goku.webservice.model;

import java.util.Date;

public class gokuUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.usercode
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.createdate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.useflag
     *
     * @mbg.generated
     */
    private String useflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_userinfo.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.userid
     *
     * @return the value of goku_userinfo.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.userid
     *
     * @param userid the value for goku_userinfo.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.usercode
     *
     * @return the value of goku_userinfo.usercode
     *
     * @mbg.generated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.usercode
     *
     * @param usercode the value for goku_userinfo.usercode
     *
     * @mbg.generated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.password
     *
     * @return the value of goku_userinfo.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.password
     *
     * @param password the value for goku_userinfo.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.username
     *
     * @return the value of goku_userinfo.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.username
     *
     * @param username the value for goku_userinfo.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.createdate
     *
     * @return the value of goku_userinfo.createdate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.createdate
     *
     * @param createdate the value for goku_userinfo.createdate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.useflag
     *
     * @return the value of goku_userinfo.useflag
     *
     * @mbg.generated
     */
    public String getUseflag() {
        return useflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.useflag
     *
     * @param useflag the value for goku_userinfo.useflag
     *
     * @mbg.generated
     */
    public void setUseflag(String useflag) {
        this.useflag = useflag == null ? null : useflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_userinfo.remarks
     *
     * @return the value of goku_userinfo.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_userinfo.remarks
     *
     * @param remarks the value for goku_userinfo.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}