package com.goku.webservice.model;

import java.io.Serializable;

public class gokuTranlogWithBLOBs extends gokuTranlog  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_tranlog.requestxml
     *
     * @mbg.generated
     */
    private byte[] requestxml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_tranlog.responsexml
     *
     * @mbg.generated
     */
    private byte[] responsexml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_tranlog.requestxml
     *
     * @return the value of goku_tranlog.requestxml
     *
     * @mbg.generated
     */
    public byte[] getRequestxml() {
        return requestxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_tranlog.requestxml
     *
     * @param requestxml the value for goku_tranlog.requestxml
     *
     * @mbg.generated
     */
    public void setRequestxml(byte[] requestxml) {
        this.requestxml = requestxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_tranlog.responsexml
     *
     * @return the value of goku_tranlog.responsexml
     *
     * @mbg.generated
     */
    public byte[] getResponsexml() {
        return responsexml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_tranlog.responsexml
     *
     * @param responsexml the value for goku_tranlog.responsexml
     *
     * @mbg.generated
     */
    public void setResponsexml(byte[] responsexml) {
        this.responsexml = responsexml;
    }
}