package com.goku.webservice.model;

public class gokuBussinessKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_bussiness.bscode
     *
     * @mbg.generated
     */
    private String bscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_bussiness.tranno
     *
     * @mbg.generated
     */
    private String tranno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_bussiness.bscode
     *
     * @return the value of goku_bussiness.bscode
     *
     * @mbg.generated
     */
    public String getBscode() {
        return bscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_bussiness.bscode
     *
     * @param bscode the value for goku_bussiness.bscode
     *
     * @mbg.generated
     */
    public void setBscode(String bscode) {
        this.bscode = bscode == null ? null : bscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_bussiness.tranno
     *
     * @return the value of goku_bussiness.tranno
     *
     * @mbg.generated
     */
    public String getTranno() {
        return tranno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_bussiness.tranno
     *
     * @param tranno the value for goku_bussiness.tranno
     *
     * @mbg.generated
     */
    public void setTranno(String tranno) {
        this.tranno = tranno == null ? null : tranno.trim();
    }
}