package com.goku.webservice.model;

public class gokuIpList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_iplist.ipaddress
     *
     * @mbg.generated
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_iplist.limitflag
     *
     * @mbg.generated
     */
    private String limitflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goku_iplist.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_iplist.ipaddress
     *
     * @return the value of goku_iplist.ipaddress
     *
     * @mbg.generated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_iplist.ipaddress
     *
     * @param ipaddress the value for goku_iplist.ipaddress
     *
     * @mbg.generated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_iplist.limitflag
     *
     * @return the value of goku_iplist.limitflag
     *
     * @mbg.generated
     */
    public String getLimitflag() {
        return limitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_iplist.limitflag
     *
     * @param limitflag the value for goku_iplist.limitflag
     *
     * @mbg.generated
     */
    public void setLimitflag(String limitflag) {
        this.limitflag = limitflag == null ? null : limitflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goku_iplist.remarks
     *
     * @return the value of goku_iplist.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goku_iplist.remarks
     *
     * @param remarks the value for goku_iplist.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}